name: Release

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major Ver.'
        required: true
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.set_output.outputs.upload_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create Release
      if: github.event_name == 'workflow_dispatch'
      id: create_release
      uses: ncipollo/release-action@v1.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ github.event.inputs.major_version }}
        name: v${{ github.event.inputs.major_version }}
        draft: false
        prerelease: false
        generateReleaseNotes: true
    - name: Set output
      id: set_output
      run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ${{ matrix.os }}
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: rust-toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
    - name: Build
      run: cargo build --release
    - name: Package (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: tar -czvf ./target/release/gradle-hash-linux-amd64.tar.gz -C ./target/release gradle-hash
    
    - name: Upload Release Asset (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./target/release/gradle-hash-linux-amd64.tar.gz
        asset_name: gradle-hash-linux-amd64.tar.gz
        asset_content_type: application/octet-stream
